# Generated by Django 4.2.6 on 2023-10-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.DateField(verbose_name='year'),
        ),
    ]
